### ISSUE TITLE
1.5.x,  it always creat a new container in html

### ISSUE THREAD

**Issue by little-eight-china** [CanopyTax/single-spa-vue#15] opened 2019-07-29 07:08 UTC
when i open the different page, it always creat a new div in html. look picture
![image](https://user-images.githubusercontent.com/27406442/62028354-a510ae00-b212-11e9-8733-dee980f00eea.png)

**Comment by joeldenning** [comment] 2019-07-29 16:03
This is a duplicate of #16. I'm going to use #16 as the issue to track this. Thanks for the details 👍

**Closed by joeldenning** 2019-07-29 16:03 UTC

**Comment by joeldenning** [comment] 2019-07-29 17:26
Fix released in https://github.com/CanopyTax/single-spa-vue/releases/tag/v1.5.3
