### ISSUE TITLE
_typeof is not defined

### ISSUE THREAD

**Issue by nightnei** [CanopyTax/single-spa-vue#23] opened 2019-11-13 13:35 UTC
**STR**:
1) clone repository
2) npm run build

**AR**: error `_typeof is not defined`

**Problem** connect with the `typeof userOpts !== 'object'`. And bundled js file has function `_typeof` inside of the umd module, instead of be defined out of the module.

**Solutions**:
1) If everything is ok on your PC, probably today we gave different versions of dependencies. Check it, please. And if I am right - add `package-lock` file.

2) And the second correct solution is to change checking for type of `userOpts` with help of using `Object.prototype.toString.call(userOpts) !== '[object Object]'`. Because your checking is incorrect, since it can't cought `arrays` and `null` values.

**Comment by joeldenning** [comment] 2019-11-13 18:24
I cannot reproduce the problem you described here. One thing is that this project uses `yarn`, not `npm`. So you should not be doing `npm install && npm run build`, but rather `yarn install && yarn build`.

I tried out both yarn and npm locally and did not see an error. What version of `node` are you using?

**Comment by nightnei** [comment] 2019-11-13 20:01
`node` version is latest.

@joeldenning Look at the bundled code please:
![Screenshot 2019-11-13 21 56 08](https://user-images.githubusercontent.com/5598437/68799520-fa0cee80-0660-11ea-9502-e1b27e2fc77a.jpg)

**Comment by nightnei** [comment] 2019-11-13 20:08
@joeldenning oh, with `yarn` we have another result. Check it please.
<img width="803" alt="Screenshot 2019-11-13 22 05 54" src="https://user-images.githubusercontent.com/5598437/68799959-da29fa80-0661-11ea-871f-731117f0647e.png">

**Comment by joeldenning** [comment] 2019-11-13 22:21
So it works for you with yarn? I'll close this issue then. I have verified that [the published version of the code](https://unpkg.com/single-spa-vue@1.5.4/lib/single-spa-vue.js) does not use the `_typeof` function outside of the scope in which it's defined.

**Closed by joeldenning** 2019-11-13 22:21 UTC

**Comment by frehner** [comment] 2019-11-13 23:22
still, pretty strange. wonder what would cause the different package managers to output a different bundle??

**Comment by joeldenning** [comment] 2019-11-14 02:55
yeah it is strange

**Comment by nightnei** [comment] 2019-11-14 08:40
@joeldenning @frehner I have found the problem.
I was right, about `lock` file. `@babel/plugin-transform-modules-umd` broke build.

You have `lock` file for `yarn`, so `yarn build` use `7.2.0` version, and `npm run build` use the latest `7.7.0` version.

Solution:
1) set `@babel/plugin-transform-modules-umd: 7.2.0`** without `^`.
2) create `lock` file for `npm`.

**Comment by frehner** [comment] 2019-11-14 13:30
Great work figuring that out. Thank you

**Comment by nightnei** [comment] 2019-11-16 15:45
@joeldenning @frehner excuse me, but I have found some more information in a commit to `umd plugin` :)
```
https://github.com/babel/babel/commit/e1839e5ec9c10ffadac51aa58fbc1e6753c6b27f#diff-ffd431f9489b95ec613d71c2ade19e4dR17
```
So, probably, you should avoid using comparison to object with help of `typeof`. And it's better to rewrite it as I did it in my first PR #24. But of course, it's up to you. It was just an interesting issue for me, so I decided to investigate problem deeply :)

**Comment by joeldenning** [comment] 2019-11-16 21:47
I read that commit and I don't understand why using `typeof` is bad.
